module.exports = {
   NOTIFICATION_TYPE: {
      GROUP: 'GROUP'
   },
   GROUP_CREATED: "GROUP_CREATED",
   USER_ADDED: "USER_ADDED",
   USER_REMOVED: "USER_REMOVED",
   USER_LEFT: "USER_LEFT",
   USER_REQUESTED: "USER_REQUESTED",
   USER_CONFIRMED: "USER_CONFIRMED",
   REQUEST_CONFIRMED: "REQUEST_CONFIRMED"
}